version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
    open-pull-requests-limit: 10 