name = "jambyte"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_COGNITO_USER_POOL_ID = "eu-west-1_h3Lu8eCZl"
NEXT_PUBLIC_COGNITO_CLIENT_ID = "18506g2uv82srnppeqn6bm673d"
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_live_51NkYOGGAlR94zWojAgPYKNLFVq4Mf7KkwmNVfPWUCo0Go8odM3jXpcYYHrqzU22p0d016hKSDqW5XpzVaecazkZn001YJBbuqU"
NEXT_PUBLIC_STRIPE_PRICE_ID = "price_1QVtp8GAlR94zWojDJgWQxD3"