'use client';

import type { Metadata } from "next";
import "./globals.css";
import Providers from '@/components/Providers';
import { Navbar } from '@/components/Navbar';
import AuthWrapper from '@/components/AuthWrapper';
import { Amplify } from 'aws-amplify';
import awsExports from '../aws-exports';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

Amplify.configure({
  Auth: {
    Cognito: {
      userPoolId: awsExports.aws_user_pools_id, // Use the value from aws-exports.js
      userPoolClientId: awsExports.aws_user_pools_web_client_id,
    }
  }
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          {children}
          <AuthWrapper />
        </Providers>
      </body>
    </html>
  );
}