'use client';

import type { Metadata } from "next";
import "./globals.css";
import Providers from '@/components/Providers';
import { Navbar } from '@/components/Navbar';
import AuthWrapper from '@/components/AuthWrapper';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          {children}
          <AuthWrapper />
        </Providers>
      </body>
    </html>
  );
}