name: Deploy App to Production

on:
  release:
    types: 
      - published
  workflow_dispatch:

env:
  NEXT_PUBLIC_COGNITO_USER_POOL_ID: ${{ vars.NEXT_PUBLIC_COGNITO_USER_POOL_ID }}
  NEXT_PUBLIC_COGNITO_CLIENT_ID: ${{ vars.NEXT_PUBLIC_COGNITO_CLIENT_ID }}
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ vars.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
  NEXT_PUBLIC_STRIPE_PRICE_ID: ${{ vars.NEXT_PUBLIC_STRIPE_PRICE_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_EMAIL: ${{ secrets.CLOUDFLARE_ACCOUNT_EMAIL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      # Setup
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      
      # Build and deploy the web app
      - name: Install dependencies
        run: pnpm install          
      - name: Build web app
        run: pnpm pages:build
        env:
          NEXT_PUBLIC_COGNITO_USER_POOL_ID: ${{ vars.NEXT_PUBLIC_COGNITO_USER_POOL_ID }}
          NEXT_PUBLIC_COGNITO_CLIENT_ID: ${{ vars.NEXT_PUBLIC_COGNITO_CLIENT_ID }}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ vars.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_STRIPE_PRICE_ID: ${{ vars.NEXT_PUBLIC_STRIPE_PRICE_ID }}
      - name: Deploy web app
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountEmail: ${{ secrets.CLOUDFLARE_ACCOUNT_EMAIL }}
          command: pages deploy --branch production

